### PR TITLE
Adds support for uploading by URL #6

### PR DESCRIPTION
**Pull request by Abbe98**

### CODE REVIEW

**Comment by yarl** [comment]
Thanks @Abbe98, have you tried to compile code and upload something?

**Comment by Abbe98** [comment]
@yarl yes.

An issue I have found so far is that the file name gets appended with a part of the URL but I'm patching it later today.

**Comment by yarl** [comment]
I've merged your code to feature branch. I had to make some changes to the code to make it fully work.
https://github.com/yarl/pattypan/commits/url-upload

@Abbe98 can you do PR to this branch in the future? Thanks :yellow_heart:

**Comment by Abbe98** [comment]
@yarl thanks,

I'm targeting `url-upload` for my coming fix.

**Pull request merged**
